name: Docker Image CD

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: check out the code base
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t gilgera/serve
